"""routing_policy

Revision ID: 1c865375ae32
Revises: c89eb127117c
Create Date: 2026-07-05 01:48:00.544698

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c865375ae32"
down_revision: str | None = "c89eb127117c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routing_policy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=True),
        sa.Column("api_key_id", sa.Uuid(), nullable=True),
        sa.Column("objective", sa.String(length=16), nullable=False),
        sa.Column("allow_providers", sa.JSON(), nullable=True),
        sa.Column("deny_providers", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_key.id"],
            name=op.f("fk_routing_policy_api_key_id_api_key"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_routing_policy_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routing_policy")),
    )
    op.create_index(
        op.f("ix_routing_policy_api_key_id"), "routing_policy", ["api_key_id"], unique=False
    )
    op.create_index(op.f("ix_routing_policy_org_id"), "routing_policy", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_routing_policy_org_id"), table_name="routing_policy")
    op.drop_index(op.f("ix_routing_policy_api_key_id"), table_name="routing_policy")
    op.drop_table("routing_policy")
    # ### end Alembic commands ###
