"""usage_record ledger

Revision ID: 52e4817988bb
Revises: 2e8a0d3c56d2
Create Date: 2026-07-05 00:47:08.634522

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52e4817988bb"
down_revision: str | None = "2e8a0d3c56d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("api_key_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_key.id"], name=op.f("fk_usage_record_api_key_id_api_key")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_record")),
    )
    op.create_index(
        op.f("ix_usage_record_api_key_id"), "usage_record", ["api_key_id"], unique=False
    )
    op.create_index(op.f("ix_usage_record_org_id"), "usage_record", ["org_id"], unique=False)
    op.create_index(
        "ix_usage_record_org_id_created_at", "usage_record", ["org_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_record_org_id_created_at", table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_org_id"), table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_api_key_id"), table_name="usage_record")
    op.drop_table("usage_record")
    # ### end Alembic commands ###
