"""usage_rollup aggregates

Revision ID: c89eb127117c
Revises: 7b1c54a073f1
Create Date: 2026-07-05 01:27:35.881301

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c89eb127117c"
down_revision: str | None = "7b1c54a073f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_rollup",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_rollup")),
        sa.UniqueConstraint("org_id", "day", name="uq_usage_rollup_org_id_day"),
    )
    op.create_index(op.f("ix_usage_rollup_org_id"), "usage_rollup", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_rollup_org_id"), table_name="usage_rollup")
    op.drop_table("usage_rollup")
    # ### end Alembic commands ###
