"""request_log replay store

Revision ID: e6119bf2d7d6
Revises: 1c865375ae32
Create Date: 2026-07-05 03:49:34.658557

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6119bf2d7d6"
down_revision: str | None = "1c865375ae32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("api_key_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_key.id"], name=op.f("fk_request_log_api_key_id_api_key")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_log")),
    )
    op.create_index(op.f("ix_request_log_api_key_id"), "request_log", ["api_key_id"], unique=False)
    op.create_index(op.f("ix_request_log_org_id"), "request_log", ["org_id"], unique=False)
    op.create_index(
        "ix_request_log_org_id_created_at", "request_log", ["org_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_request_log_org_id_created_at", table_name="request_log")
    op.drop_index(op.f("ix_request_log_org_id"), table_name="request_log")
    op.drop_index(op.f("ix_request_log_api_key_id"), table_name="request_log")
    op.drop_table("request_log")
    # ### end Alembic commands ###
